-- Active: 1728688414725@@127.0.0.1@3306@ec1_si1n
#FASE 1: CRIAR O BANCO DE DADOS (SCHEMA OU DATABASE):
#MEU PRIMEIRO BANQUINHO
#CREATE SCHEMA EC1_SI1N;

#FASE 2: SELECIONAR O NOVO SCHEMA OU DATABASE PARA USO:
#USANDO MEU BANQUINHO
USE EC1_SI1N;


# FASE 3: CRIANDO AS TABELAS SEM CHAVES ESTRANGEIRAS

#CRIANDO A TABELINHA FORNECEDORES
DROP TABLE FORNECEDORES;
CREATE TABLE IF NOT EXISTS FORNECEDORES(
#NOMEDOATRIBUTO - TIPO - RESTRIÇÃO DE INTEGRIDADE(OPCIONAL)
FORNEC_COD INT PRIMARY KEY,
FORNEC_NOME VARCHAR(45)NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45),
FORNEC_ESTADO VARCHAR(45),
FORNEC_PAIS VARCHAR(30),
FORNEC_CODPOSTAL VARCHAR(10),
FORNEC_TELEFONE VARCHAR(15) ,
FORNEC_CONTATO TEXT 
);
ALTER TABLE FORNECEDORES
ADD COLUMN FORNEC_CNPJ VARCHAR(14) NOT NULL;
ALTER TABLE FORNECEDORES
CHANGE COLUMN FORNEC_NUMRUA FORNEC_NUMERORUA  VARCHAR(10) NOT NULL;
ALTER TABLE FORNECEDORES
CHANGE COLUMN FORNEC_NUMERORUA FORNEC_NUMRUA INT NOT NULL;
ALTER TABLE FORNECEDORES
DROP COLUMN FORNEC_NOME;
ALTER TABLE FORNECEDORES
MODIFY COLUMN FORNEC_RUA VARCHAR(50);


#CRIANDO A TABELINHA FILIAIS
DROP TABLE FILIAIS;
CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAL_COD INT PRIMARY KEY,
FILIAL_NOME VARCHAR(45) NOT NULL,
FILIAL_RUA VARCHAR(100) NOT NULL,
FILIAL_NUMRUA INT,
FILIAL_BAIRRO VARCHAR(50) NOT NULL,
FILIAL_CIDADE VARCHAR(50) NOT NULL,
FILIAL_ESTADO VARCHAR(50) NOT NULL,
FILIAL_PAIS VARCHAR(50) NOT NULL,
FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
FILIAL_CAPACIDADE INT NOT NULL);

ALTER TABLE FILIAIS
ADD COLUMN FILIAL_TELEFONE VARCHAR(15);

ALTER TABLE FILIAIS
CHANGE COLUMN FILIAL_TELEFONE FILIAL_CONTATO VARCHAR(20);

ALTER TABLE FILIAIS
CHANGE COLUMN FILIAL_CONTATO FILIAL_TELEFONE VARCHAR(20);
ALTER TABLE FILIAIS
DROP COLUMN FILIAL_CONTATO;
ALTER TABLE FILIAIS
MODIFY COLUMN FILIAL_NOME VARCHAR(30);


#CRIANDO A TABELINHA PRODUTOS
DROP TABLE PRODUTOS;
CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_QUANT DECIMAL(10,3),
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDMEDIDA VARCHAR(15) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

ALTER TABLE PRODUTOS
ADD COLUMN PROD_CATEGORIA VARCHAR(30) NOT NULL;

ALTER TABLE PRODUTOS
CHANGE COLUMN PROD_CATEGORIA PROD_TIPO VARCHAR(50);

ALTER TABLE PRODUTOS
CHANGE COLUMN PROD_TIPO PROD_CATEGORIA VARCHAR(30);

ALTER TABLE PRODUTOS
DROP COLUMN PROD_CATEGORIA;

ALTER TABLE PRODUTOS
MODIFY COLUMN PROD_PRECOUNIT DECIMAL(12,2) NOT NULL;

#FASE 4: CRIAR AS TABELAS COM DEPENDÊNCIA DE CHAVE ESTRANGEIRA

#CRIANDO A TABELA PEDIDOS
DROP TABLE IF EXISTS PEDIDOS;

CREATE TABLE IF NOT EXISTS PEDIDOS (
    PED_CODIGO INT PRIMARY KEY,
    PED_DATA DATE NOT NULL,
    PED_HORA TIME NOT NULL,
    PED_PREVISAO DATE NOT NULL,
    PED_STATUS ENUM('PENDENTE', 'CONCLUÍDO', 'EM ESPERA'),
    Fornec_COD INT,
    #NOSSA CHAVE ESTRANGEIRA DE FORNECEDOR
    #CRIANDO A REFERENCIA PARA A CHAVE ESTRANGEIRA
    #RESTRIÇÃO APELIDO CH.ESTRANGEIRA(CAMPO CRIADO) REFERENCIA TABELA(CH.PRIMÁRIA)
    CONSTRAINT FK_For_Ped FOREIGN KEY (Fornec_COD)
    #DAR NOME A RESTRIÇÃO(CONSTRAINT) É UMA BOA PRÁTICA
    REFERENCES FORNECEDORES(FORNEC_COD)
    #REFERENCIA A CHAVE PRIMÁRIA DE FORNECEDORES
);
ALTER TABLE PEDIDOS
ADD COLUMN PED_ENVIO DATE NOT NULL;

ALTER TABLE PEDIDOS
CHANGE COLUMN PED_PREVISAO PED_PREV DATE NOT NULL;

ALTER TABLE PEDIDOS
CHANGE COLUMN PED_PREV PED_PREVISAO DATE NOT NULL;
ALTER TABLE PEDIDOS
DROP COLUMN PED_ENVIO;
ALTER TABLE PEDIDOS
MODIFY COLUMN PED_ENVIO DATETIME NOT NULL;

DROP TABLE RECEBIMENTOS;
CREATE TABLE IF NOT EXISTS RECEBIMENTOS (
    RECEB_PEDIDOS INT PRIMARY KEY,
    RECEB_DATA DATE NOT NULL,
    RECEB_HORA TIME NOT NULL,
    RECEB_QUANT_PROD DECIMAL(10,3),
    RECEB_CONDICAO TEXT NOT NULL,
    PED_Codigo INT,
    CONSTRAINT FK_PEDIDOS FOREIGN KEY(PED_Codigo) 
    REFERENCES PEDIDOS(PED_CODIGO)
);

ALTER TABLE RECEBIMENTOS
CHANGE COLUMN RECEB_CONDICAO RECEB_COND TEXT NOT NULL;

ALTER TABLE RECEBIMENTOS
CHANGE COLUMN RECEB_COND RECEB_CONDICAO TEXT NOT NULL;
ALTER TABLE RECEBIMENTOS
ADD COLUMN RECEB_TENTATIVAS INT NOT NULL;

ALTER TABLE RECEBIMENTOS
DROP COLUMN RECEB_TENTATIVAS;
ALTER TABLE RECEBIMENTOS
MODIFY COLUMN RECEB_TENTATIVAS FLOAT NOT NULL;

#FASE 5: CRIANDO AS TABELAS ASSOCIATIVAS (ENTIDADES ASSOCIATIVAS)

#CRIANDO A TABELA PEDIDOS_PRODUTOS
DROP TABLE IF EXISTS PEDIDOS_PRODUTOS;
CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PDPR_PEDIDOS INT,
PDPR_PRODUTOS INT,
PRIMARY KEY(PDPR_PEDIDOS,PDPR_PRODUTOS),
CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO),
CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY(PDPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);
ALTER TABLE PEDIDOS_PRODUTOS
CHANGE COLUMN PDPR_PEDIDOS PDPR_PED INT NOT NULL;

ALTER TABLE PEDIDOS_PRODUTOS
CHANGE COLUMN PDPR_PED PDPR_PEDIDOS INT NOT NULL;

ALTER TABLE PEDIDOS_PRODUTOS
ADD COLUMN PDPR_QTD INT NOT NULL;

ALTER TABLE PEDIDOS_PRODUTOS
DROP COLUMN PDPR_QTD;
ALTER TABLE PEDIDOS_PRODUTOS
MODIFY COLUMN PDPR_PEDIDOS FLOAT NOT NULL;

#CRIANDO A TABELA FILIAIS_PRODUTOS
DROP TABLE IF EXISTS FILIAIS_PRODUTOS;
CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FLPR_FILIAL INT,
FLPR_PRODUTOS INT,
PRIMARY KEY(FLPR_FILIAL,FLPR_PRODUTOS),
CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY(FLPR_FILIAL) REFERENCES FILIAIS(FILIAL_COD),
CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY(FLPR_PRODUTOS) 
REFERENCES PRODUTOS(PROD_COD)
);
ALTER TABLE FILIAIS_PRODUTOS
CHANGE COLUMN FLPR_FILIAL FLPR_FILIAIS INT NOT NULL;

ALTER TABLE FILIAIS_PRODUTOS
CHANGE COLUMN FLPR_FILIAIS FLPR_FILIAL INT NOT NULL;

ALTER TABLE FILIAIS_PRODUTOS
ADD COLUMN FLPR_QTD INT NOT NULL;

ALTER TABLE FILIAIS_PRODUTOS
DROP COLUMN FLPR_QTD;
ALTER TABLE FILIAIS_PRODUTOS
MODIFY COLUMN FLPR_PRODUTOS FLOAT NOT NULL;
#CRIAR A TABELA FORNECEDORES_PRODUTOS
DROP TABLE IF EXISTS FORNECEDORES_PRODUTOS;
CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
    Fornec_COD INT,
    Prod_COD INT,
    PRIMARY KEY(Fornec_COD, Prod_COD),
    CONSTRAINT FORPROD_FK_FORNE FOREIGN KEY(Fornec_COD) REFERENCES FORNECEDORES(FORNEC_COD),
    CONSTRAINT FORPROD_FK_PROD FOREIGN KEY(Prod_COD) REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE FORNECEDORES_PRODUTOS
CHANGE COLUMN Fornec_COD FORNEC_CODIGO INT;

ALTER TABLE FORNECEDORES_PRODUTOS
CHANGE COLUMN FORNEC_CODIGO Fornec_COD INT;

ALTER TABLE FORNECEDORES_PRODUTOS
ADD COLUMN Fornec_COD_QTD INT NOT NULL;

ALTER TABLE FORNECEDORES_PRODUTOS
DROP COLUMN Fornec_COD_QTD;
ALTER TABLE FORNECEDORES_PRODUTOS
MODIFY COLUMN Prod_COD FLOAT NOT NULL;
